apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Delete=confirm
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: addons/external-secrets
    repoURL: https://github.com/34fathombelow/argocd-akuity-helm.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true